/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GuwMyStencilWidget {
        "metadata": string;
        "value": number;
    }
}
export interface GuwMyStencilWidgetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLGuwMyStencilWidgetElement;
}
declare global {
    interface HTMLGuwMyStencilWidgetElement extends Components.GuwMyStencilWidget, HTMLStencilElement {
    }
    var HTMLGuwMyStencilWidgetElement: {
        prototype: HTMLGuwMyStencilWidgetElement;
        new (): HTMLGuwMyStencilWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "guw-my-stencil-widget": HTMLGuwMyStencilWidgetElement;
    }
}
declare namespace LocalJSX {
    interface GuwMyStencilWidget {
        "metadata"?: string;
        "onValueChange"?: (event: GuwMyStencilWidgetCustomEvent<any>) => void;
        "value"?: number;
    }
    interface IntrinsicElements {
        "guw-my-stencil-widget": GuwMyStencilWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "guw-my-stencil-widget": LocalJSX.GuwMyStencilWidget & JSXBase.HTMLAttributes<HTMLGuwMyStencilWidgetElement>;
        }
    }
}
